add basic rxp for endless
mohamadnosratian/Fortress-defense pull request #111
Opened 2024-01-31 16:28 UTC by amirsafaricg

2024-01-31 16:48 UTC, m-nt commented on Assets/_FD/Script/GiveExpWhenDie.cs
> +    private bool _isEndless = false;
داری endless بودن رو توی GiveExpWhenDie چک میکنی،
مشکلاتش اینه:
 این کد در پایین ترین لول داره اجرا میشه، یعنی روی همه 200 و خورده ای enemy هست به عنوان component و اجرای این کد نیازمند تغییر کل prefab دشمنا هست، بهتره از لول بالاتر انجامش بدی، مثلا جایی که کد GiveExp داره فراخونی میشه یا اینکه چک کردن اینکه endless هست یا نه رو بذار توی لول بالاتر چک کنی مثلا اینجا :
`Assets/_FD/Scripts/LevelWaves.cs line:8`  این کد خودتم هست.

2024-01-31 16:49 UTC, m-nt commented on Assets/Atlas games/Scripts/User.cs
> +    public static int RxpTotal
توضیح بده که هدف RxpTotal چیه ! چون که دقیقا مشابه rxp کار میکنه.

2024-01-31 17:10 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/User.cs
> +    public static int RxpTotal
Rxp total 
رو برای این گذاشتم کل rxp های کاربر رو تو اندلس جمع کنیم، اون یکی مختص رکورد زنیه 
این rxp کله که هادی گفت میخواد داشته باشیم جدا یه جایی برای آینده

2024-02-02 06:05 UTC, amirsafaricg commented on Assets/_FD/Script/GiveExpWhenDie.cs
> +    private bool _isEndless = false;
انجام شد، منطقش رو به GameManager.cs انتقال دادم.

2024-02-03 14:51 UTC, amirsafaricg commented
Rxp total : با بازی کردن در اندلس rxp کاربر جمع میشه و مربوط به یک بازی نیست و هرچقدر بازی کنه این متغیر بیشتر میشه 

Rxp : به صورت رکوردی ثبت میشه بعنوان مثال اگر در یک دور بازی اندلس به rxp 100 برسه 
دفعه بعدی که بازی کنه باید حتما بیشتر از 100 rxp بدست بیاره که بتونه دوباره مقدار جدیدی براش ثبت بشه 

این موارد طبق دستورات آقا هادی بودن

2024-02-03 17:34 UTC, amirsafaricg commented
لیست نمایش دادن لیدربورد رو هم در آوردم منوشو هم ساختم به Home Menu اضافه کردم. 
حالا باید تستش کنم ببینم مشکلی توش هست یا خیر

2024-02-06 15:52 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/DownloadImage.cs
> +}
آخر همه فایل ها یه خط خالی اضافه کن، این قانون گیتهابه، ببین داره ایراد میگیره :
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/f9e445b2-e8be-49de-87e6-45910f3de814)

2024-02-06 15:52 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/Editor/InfiniteScrollEditor.cs
> +}
اینم همینطور

2024-02-06 16:00 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderBoard.cs
> +    public static class JsonHelper
این کلاس کلا کارش بی معنیه، کلاس هایی که به عنوان T داده میشه به JsonUtility خودشون Serializable هستن.
و اینکه بجای این از JsonConvert.DeserializeObject استفاده کن، بهتره

2024-02-06 16:03 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderBoard.cs
> +        value = "{\"Items\":" + value + "}";
از format string استفاده کن :
```c#
value = $"{'Items':{value}}"
```

2024-02-06 16:04 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderBoard.cs
> +    IEnumerator GetData()
نیازی نیست هر دفعه اینو بنویسی، APIManager هست برای این کار Get , Post داره گه فعلا بیشتر از این نیازی نداریم.

2024-02-06 16:05 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderBoard.cs
> +}
New Line in End of line

2024-02-06 16:05 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderboardList.cs
> +}
New Line in End of file

2024-02-06 16:07 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderboardListItem.cs
> +public class LeaderboardListItem : MonoBehaviour
آیتم های leaderboard میتونه یه کلاس سریالایز شده باشه تا توی تبدیل از جسون به مدل راجت تر باشی

2024-02-06 16:19 UTC, m-nt commented on Assets/_FD/Script/GUI/MainMenuHomeScene.cs
> +            LeaderBoardUI.SetActive(open);
یه پیشنهاد.
اول اینکه LeaderBoardUI رو داری دوبار استفاده میکنی در صورتی که کارش مشابه و هیچ ربطی به شرط نداره.
بعد اینکه side effect این متد ممکنه خطرناک باشه، مثلا یکی چند بار این متد رو صدا بزنه با مقدار open هه true باعث میشه که عملایت ClearList اتفاق نیوفته و رکورد های تکراری داشته باشی، 
از روش بازگشت زودهنگام استفاده کن تا side effect کم بشه.
```c#
public void OpenLeaderBoard(bool open) {
    LeaderBoardUI.SetActive(open);
    if (open) {
        LeaderBoard leaderBoard = LeaderBoardUI.GetComponent<LeaderBoard>();
        leaderBoard.ClearList();
        leaderBoard.LoadLeaderboard();
    }
}
```
این مدل پیشنهای منه، اینطوری فقط هر دفعه که قراره لیدربورد رو نمایش بدی یبار clear میکنی و نمایش میدی، دیگه sideeffect نداره و تنها وقتی چیزی نمایش میدی که open مقدارش true هست

2024-02-06 16:20 UTC, m-nt commented on Assets/_FD/Script/GameManager.cs
> +        if (GameLevelSetup.Instance.type() == LevelWave.LevelType.Endless)
اینجا هم همین، تو استفاده از if و else پشت هم خیلی دقت کن که side effect نداشته بشه، اینجا هم میشه ساده ترش کرد ولی نکردی هم مشکلی نداره.

2024-02-06 16:21 UTC, m-nt requested changes
تغییرات لازمه، کامنت هارو بخون

2024-02-12 10:12 UTC, amirsafaricg commented on Assets/_FD/Script/GUI/MainMenuHomeScene.cs
> +            LeaderBoardUI.SetActive(open);
چرا داره
Clear list 
اگر لیدربورد ما set active اش false باشه انجام نمیشه چون غیرفعاله اونوقت 
این شرط برای اینه که ترتیب انجام کارها درست باشه 


موقع بستن منوی لیدربورد باید قبل از setactive(false) کارهایی که داخل اسکریپت Leaderboard هستن رو انجام بده و بالعکس

2024-02-12 10:12 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderboardListItem.cs
> +public class LeaderboardListItem : MonoBehaviour
انجام شد

2024-02-12 10:17 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderBoard.cs
> +        value = "{\"Items\":" + value + "}";
خطا میده اینی که شما پیشنهاد دادین.

2024-02-12 10:59 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/LeaderBoard/DownloadImage.cs
> +public class DownloadImage : MonoBehaviour
درستش کردم.

2024-02-12 11:00 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderBoard.cs
> +    IEnumerator GetData()
فعلا گذاشتم باشه تا بعدا جایگزینش کنیم.

2024-02-12 11:19 UTC, amirsafaricg commented
کامیت جدید رو چک بفرمایید.

2024-02-17 14:26 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderBoard.cs
> +        value = "{\"Items\":" + value + "}";
اره اشتباه نوشتم اینطوری درسته :
```c#
value = $"{{Items':{value}}}"
```
اررورش از اینه که چون } توی متن هست باید scape بشه و روش c# برای scape کردن دوبار نوشتنه. درواقع `{value}` موردی هست که از متقییر value استفاده میکنه و بعقیه {/} ها جزوی از متنه

2024-02-17 15:06 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderBoard.cs
> +                json = fixJson(json);
کدت رو اجرا کردم، این خط باعث اررور میشه چون توی خط 55 داری Array میگیری.
تمرین مناسب برای اینکه مطمعن بشی Deserialize شدن درست انجام بشه اینه که از try catch استفاده کنی و توی catch از `APIManager.instance.RunStatus` استفاده کن برای نمایش اررور و مثلا صفحه لیدربورد رو ببند، چون اگه دیتایی که از سرور میاد درست نباشه مشکل باید سمت سرور حل بشه نه ما، validation سمت ما درست نیست.

2024-02-17 15:12 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderBoard.cs
> +                Array.Sort(_dataArray, (x, y) => y.rxp.CompareTo(x.rxp));
به جای Array.sort هم میتونی کلا List بگیری، حالا زیاد اهمیتی نداره چون قرار نیست sort کنیم ولی List خیلی بهینه تر انجام میده در اندازه های کوچیک، اینطوری :
```c#
leaderBoards = JsonConvert.DeserializeObject<List<LeaderboardData>>(json);
// the next line is not necessary ...
// Array.Sort(leaderBoards.s, (x, y) => y.rxp.CompareTo(x.rxp));
listOfUsers.data = leaderBoards.OrderBy((x) => x.rxp).ToArray();
```

2024-02-17 15:13 UTC, m-nt requested changes
به جز یه مورد بعقیه اوکیه، فقط مونده اضافه شدن بک اند و UI ها. فعلا تو حالت درخواست تغییر نگه میداریم تا اونها هم درست بش

2024-03-11 15:07 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderboardListItem.cs
> +       SetImage(data.user_avatar);
از این فانکشن فقط یک بار استفاده کردی برای چی اصلا فاکنشنه و مستقیم از `APIManager.instance.Get_rofile_picture(url)` این استفاده نکردی وقتی `SetImage` فقط یک بار استفاده شده ؟

2024-03-11 15:11 UTC, m-nt commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderboardListItem.cs
>      async void SetImage(string url)
توی این متد خط 22 این اررور رو داری :
`NullReferenceException: Object reference not set to an instance of an object`
آبجکت اش هم اینطوریه
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/7d51b8a8-e823-4674-a3d2-1a26461a3e50)

2024-03-11 15:11 UTC, m-nt requested changes
تغییر لازمه

2024-03-12 06:07 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderboardListItem.cs
>      async void SetImage(string url)
image اساین شد  و رفع شد

2024-03-12 06:07 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/LeaderBoard/LeaderboardListItem.cs
> +       SetImage(data.user_avatar);
بخاطر async

2024-03-12 12:07 UTC, m-nt commented on Assets/Atlas games/Fonts/Digi Madasi Bold SDF.asset
تغییر بی دلیل روی فایل، اصلاح بشه لطفا

2024-03-12 12:22 UTC, m-nt commented on Assets/Atlas games/Scene/Menu atlas Test.unity
> +      value: 1
منوی بازی روی LeaderBoard باز میشه، لطفا اصلاح کن اینو

2024-03-12 12:26 UTC, m-nt commented on Assets/Atlas games/Scripts/APIManager.cs
> +    public async Task<AchievementModel> Get_achivements()
دلیل این تغییر چیه ؟

2024-03-12 12:32 UTC, m-nt commented on Assets/_FD/Font/Blood'n Guts SDF.asset
تغییر بی دلیل روی فایل، اصلاح بشه لطفا

2024-03-12 12:36 UTC, m-nt requested changes
موارد بررسی شود

2024-03-23 21:41 UTC, closed without merging