day/night mode
mohamadnosratian/Fortress-defense pull request #112
Opened 2024-02-06 14:20 UTC by amirsafaricg

added these features : 
- changing the given exp from enemies in night mode and increasing them with multiplier value
- adding a global value for night mode 
- adding night mode and night mode xp multiplier to the level generator 
- tested level editing 
- applying these features on endless mode.

2024-02-06 14:39 UTC, m-nt commented on Assets/GeneratedLevels/Level 33.prefab
> -  level: 33
دلیلت برای تغییر مرحله 33 چی بود ؟

2024-02-06 14:40 UTC, m-nt commented on Assets/GeneratedLevels/Level 33.prefab
> +  enemiesList: []
اینجا لیست enemy ها رو خالی کردی

2024-02-06 14:40 UTC, m-nt commented on Assets/GeneratedLevels/Level 33.prefab
> -    - wait: 0
و اینجا هم آبجکت هاشو پاک کردی

2024-02-06 14:41 UTC, amirsafaricg commented on Assets/GeneratedLevels/Level 33.prefab
> -    - wait: 0
فکر کنم چون بلد نبودم با این اسکریپت کار کنم، حواسم نبود همه پارامترهاشو باید ست کنم بعد باهاش ور برم 
از رو برنچ های دیگه کپیش میکنم مشکلی نیست 

میخواستم فقط تست کنم گزینه نایت مود و مولتی پلایرش میشینه یا نه

2024-02-06 14:47 UTC, m-nt commented on Assets/_FD/Script/GlobalValue.cs
> +            if (value)
اینو پیشنهاد میدم از قابلیت تک خط نویسی سیشارپ استفاده کنی :
```c#
PlayerPrefs.SetInt("Night", value ? 1 : 0 );
```
این لینک برای مطالعه بیشتر : [the ternary conditional operato](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-operator)

2024-02-06 15:28 UTC, m-nt commented on Assets/Atlas games/Scripts/EndlessWaveGenerator.cs
> +                                GameLevelSetup.Instance.NightModeXpMultiplier());
اینجا داری برای هر دشمن سه بار این حلقه رو اجرا میکنی.
```c#
foreach (var obj in levelWaves)
{
    if (obj.level == GlobalValue.levelPlaying)
        return obj.nightXpMultiplier;
}
```
که بهینه نیست اصلا. درصورتی که راه بیهنش اینه که مشابه ست کردن LevelWaves توی GameLevelSetup که داخل متد Start روی کد LevelEnemyManager  خط 32 میگیری، این رو هم توی استارت لول ست کنی توی متغییر های LevelEnemyManager و EndlessWaveGenerator تا نیاز نباشه هر دفعه این متعییر رو چک کنی با foreach. در کل منظروم اینه که یبار توی استارت این script انجامش بده بجای هر بار call کردنش

2024-02-06 15:32 UTC, m-nt commented on Assets/_FD/Script/GUI/GameLevelSetup.cs
> +        return 9999;
این چرا پیشفرضش 9999 هست ؟ پیشفرش 1 باید باشه که با ضرب در health خودش رو بده، یعنی بی تاثیر بشه.

2024-02-06 15:33 UTC, m-nt requested changes
تغییر لازمه!

2024-02-12 11:10 UTC, amirsafaricg commented on Assets/_FD/Script/GlobalValue.cs
> +            if (value)
Done

2024-02-12 11:12 UTC, amirsafaricg commented on Assets/_FD/Script/GUI/GameLevelSetup.cs
> +        return 9999;
Done

2024-02-12 11:16 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/EndlessWaveGenerator.cs
> +                                GameLevelSetup.Instance.NightModeXpMultiplier());
گذاشتمش تو استارت.

2024-02-12 11:16 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/EndlessWaveGenerator.cs
> +                            _temp.GetComponent<SmartEnemyGrounded>().health = Mathf.RoundToInt(_temp.GetComponent<SmartEnemyGrounded>().health *
تایپمون int هست اگر یه ضریب که float باشه داشته باشیم باید روند کنیم که خب اینطوری خلاصه ترین حالتشه

2024-02-12 11:19 UTC, amirsafaricg commented
کامیت جدید رو چک بفرمایید

2024-02-12 16:34 UTC, m-nt commented on Assets/Atlas games/Scripts/EndlessWaveGenerator.cs
> +                            GameLevelSetup.Instance.NightModeXpMultiplier());
الان چه تفاوتی ایجاد شد با قبلی ؟ بازم داری `()GameLevelSetup.Instance.NightModeXpMultiplier` رو برای هر دشمن صدا میزنی که توش `for` داره، هدف این بود که اینو توی `Start` اجرا کنی، چون حلقه تو وابسطه به اینه که توی کدوم لول هستی، وقتی توی لول رفتی چه نیازیه هر دفعه برای هر دشمن چک کنی اینو وقتی اطلاعاتش سابته توی کله پروسه ایجاد دشمنا ؟

2024-02-12 16:35 UTC, m-nt commented on Assets/_FD/Script/SpawnEnemyManager/LevelEnemyManager.cs
>                                      GameLevelSetup.Instance.NightModeXpMultiplier());
همینطور اینجا

2024-02-12 16:35 UTC, m-nt requested changes
تغییر نیازه

2024-02-12 16:37 UTC, m-nt commented on Assets/GeneratedLevels/Level 33.prefab
> -    - wait: 0
لطفا از برنچ های دیگه کپی نکن، اطلاعتش توی commit های قبلی همین برنچ هست، سعی کن از خود گیت استفاده کنی

2024-02-13 16:18 UTC, amirsafaricg commented on Assets/_FD/Script/SpawnEnemyManager/LevelEnemyManager.cs
>                                      GameLevelSetup.Instance.NightModeXpMultiplier());
حل شد

2024-02-13 16:35 UTC, m-nt reviewed
فعلا حله، ادامه بده

2024-05-01 17:32 UTC, m-nt requested changes
مشکل خاص دیگه ای ندیدم، لطفا تکلیف پیام های بالاتر رو هم مشخص کن.

2024-05-16 07:34 UTC, amirsafaricg commented
@m-nt 
سلام 
آیتم دابل ایکس پی رو پیاده کردم همراه با لاجیک مود روز و شب 
یخورده با کدهای تمیز تر و همچنین آیتم دابل ایکس پی موقت 1 روزه و 1 ساعته به همراه سیستم جلوگیری از تقلب
بی زحمت کدها رو چک بفرمایید.

2024-05-26 19:04 UTC, m-nt requested changes

2024-05-26 19:04 UTC, m-nt commented on Assets/_FD/Script/SpawnEnemyManager/LevelEnemyManager.cs
> +                                throwAttack.damage = enemySpawn.customAttackDmg;
اینا تغییر نکرده فقط مجدد format شده درسته ؟

2024-07-19 13:36 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +        if (GlobalValue.DoubleXp)
Done

2024-07-19 13:36 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +}
Done

2024-07-19 13:36 UTC, amirsafaricg commented on Assets/_FD/Script/LevelWave.cs
>  }
Done

2024-07-19 13:54 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +            int year = int.Parse(insertedTime.Substring(0, 4));
با اون کار در نمیاد کلا برای همین دیگه وقت بیشتر سرش صرف نمیکنم بریم سر چیزای مهم

2024-07-20 05:48 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +        CheckDoubleXpStatus();
این فانکشن async هست ولی معمولی استفاده شده اینجا!

2024-07-20 05:48 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +    }
دلیل async بودن این فاکشن چیه ؟

2024-07-20 05:49 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +                                                              newDifferenceSeconds);
برای PlayerPrefs ها از GlobalValues استفاده کن اونجا اضافش کن و ازش استفاده کن لطفا.

2024-07-20 05:50 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +}
آخر فایل new line بزار

2024-07-20 05:50 UTC, m-nt commented on Assets/Atlas games/Scripts/EndlessWaveGenerator.cs
> +   new int _totalEnemy, _currentSpawn;
وقتی new گذاشتی نیازی نبود دیگه اسمشو ویرایش میکردی ولی مشکلی نیست.

2024-07-20 05:51 UTC, m-nt commented on Assets/_FD/Script/LevelWave.cs
> +}
آخر فایل new line بزار

2024-07-20 05:51 UTC, m-nt requested changes
تغییر لازمه

2024-07-20 05:52 UTC, m-nt requested changes
تغییر لازمه

2024-07-20 05:55 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +    }
ببین async await برای concurrency هست و اینجا تو مستقیم توی آپدیت صدا زدی اینو یعنی فقط overhead های ساختن آبجکت Task رو داری و هیچ تفاوتی با حالت عادی نداره این فانکشنت! اگر دلیل خواستی داشتی برای async شدنش بگو راهنمایی کنم

2024-07-20 06:04 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +        DontDestroyOnLoad(gameObject);
اینو حواست باشه که آبجکتش کجا هست اگر توی سکانسی باشه که کاربر برمیگرده بهش مثل home menu این خط کد باعث میشه که کد duplicate بشه. اینو لطفا برای بعقیه هم بررسی کن، برای حل این مشکل از singleton استفاده کن برای بررسی اینکه باید اینو فعال کنی یا نه.
 تستی که گرفتم :
![image](https://github.com/user-attachments/assets/1d5098e5-1c1a-499b-8e37-7f14e4025771)

2024-07-20 06:21 UTC, m-nt commented
لطفا پریفب HomeMenu رو هم تمیز نگه دار :
![image](https://github.com/user-attachments/assets/7f0363e4-ddb0-4669-949c-4f70920b9821)

2024-07-20 06:24 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/EndlessWaveGenerator.cs
> +   new int _totalEnemy, _currentSpawn;
پاک شد

2024-07-20 06:25 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +}
done

2024-07-20 06:26 UTC, amirsafaricg commented on Assets/_FD/Script/LevelWave.cs
> +}
قبلا گذاشتم :)

2024-07-20 06:27 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +    }
شما گفته بودین : 
![Screenshot 2024-07-20 095552](https://github.com/user-attachments/assets/66d219d5-8d87-4228-9eb2-e96199c00d22)

2024-07-20 06:29 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +        DontDestroyOnLoad(gameObject);
![Screenshot 2024-07-20 095827](https://github.com/user-attachments/assets/0e8386d2-e402-41b6-b181-ed52635fbad2)

این آبجکت فقط تو منو اطلس هست 
و وقتی میریم صحنه های دیگه و برمیگردیم فقط همینه 
باید همین شکلی باشه که دابل ایگس پی کار کنه

2024-07-20 06:29 UTC, amirsafaricg commented
> لطفا پریفب HomeMenu رو هم تمیز نگه دار : ![image](https://private-user-images.githubusercontent.com/68176509/350669050-7f0363e4-ddb0-4669-949c-4f70920b9821.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NTY3OTIsIm5iZiI6MTcyMTQ1NjQ5MiwicGF0aCI6Ii82ODE3NjUwOS8zNTA2NjkwNTAtN2YwMzYzZTQtZGRiMC00NjY5LTk0OWMtNGY3MDkyMGI5ODIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA2MjEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODcwNzQwZjdkNzBlMzUwYzcxOGU3YzNmMzAxYjUwNGJmY2JiYjdlNDhiMWM0ZWM5MWRhNjU2MjEwYjBhNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._yAO10dvk6Z9yySNxbVzJD58KqKabkPo4lkarYcm_48)


صرفا برای توسعه اونم فقطط روی همین برنچه 
دو تا دکمه‌اس بعد اینکه کارمون تموم شه میتونیم پاکشون کنیم راحت بذارید فعلا همینجا باشن.

2024-07-20 06:30 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +        CheckDoubleXpStatus();
به کلی حذف شد برگشت به حالتی که قبلا بود.

2024-07-20 07:06 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +                                                              newDifferenceSeconds);
انجام شد

2024-07-20 07:07 UTC, amirsafaricg commented
@m-nt 
تغییرات رو چک کنید تشکر

2024-07-21 05:39 UTC, m-nt commented
> > لطفا پریفب HomeMenu رو هم تمیز نگه دار : ![image](https://private-user-images.githubusercontent.com/68176509/350669050-7f0363e4-ddb0-4669-949c-4f70920b9821.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NTY3OTIsIm5iZiI6MTcyMTQ1NjQ5MiwicGF0aCI6Ii82ODE3NjUwOS8zNTA2NjkwNTAtN2YwMzYzZTQtZGRiMC00NjY5LTk0OWMtNGY3MDkyMGI5ODIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA2MjEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODcwNzQwZjdkNzBlMzUwYzcxOGU3YzNmMzAxYjUwNGJmY2JiYjdlNDhiMWM0ZWM5MWRhNjU2MjEwYjBhNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._yAO10dvk6Z9yySNxbVzJD58KqKabkPo4lkarYcm_48)
> 
> صرفا برای توسعه اونم فقطط روی همین برنچه دو تا دکمه‌اس بعد اینکه کارمون تموم شه میتونیم پاکشون کنیم راحت بذارید فعلا همینجا باشن.

صرفا برای توسعه مشکلی نداره ولی حواست باشه اینا مرج نشه

2024-07-21 05:49 UTC, m-nt commented on Assets/_FD/Script/GlobalValue.cs
> +        get { return PlayerPrefs.GetString("DoubleXp1HourDurationActivationTime", "0001-01-0000:00:00"); }
اینو بذار تاریخ epoch که یوقت جایی به مشکل نخوریم اینه:
`1970-01-01T00:00:01.0000z`

2024-07-21 05:50 UTC, m-nt requested changes
از نظر کدی خوبه! تمیز کاری هارو انجام بده بره برای مرج

2024-07-21 05:50 UTC, m-nt commented
کانفلیکت هم داری

2024-08-24 04:55 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +        DontDestroyOnLoad(gameObject);
برای اطمینان از اینکه فقط یکی از این آبجکت داشته باشیم.
```suggestion
    public static DoubleXPManager self;
    async void Awake()
    {
        if (self == null){
            self = this;
            DontDestroyOnLoad(this);
        } else {
            Destroy(this);
        }
```

2024-08-24 05:25 UTC, m-nt commented on Assets/_FD/Script/GlobalValue.cs
> +        get { return PlayerPrefs.GetString("DoubleXp1HourDurationActivationTime", "0001-01-0000:00:00"); }
```suggestion
        get { return PlayerPrefs.GetString("DoubleXp1HourDurationActivationTime", "1970-01-0100:00:01"); }
```
این باید بدین صورت تغییر کنه!
وقتی زمان رو 0001 میزاری این زمان خارج از برد اسکریپت Datetime هست و اررور میده.
```bash
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
  at System.DateTime.DateToTicks (System.Int32 year, System.Int32 month, System.Int32 day) [0x00077] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.DateTime..ctor (System.Int32 year, System.Int32 month, System.Int32 day, System.Int32 hour, System.Int32 minute, System.Int32 second) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at DoubleXPManager.ConvertedStringToDate (System.String insertedTime) [0x0005b] in D:\Projects\Hadi\fortress-defense\Assets\Atlas games\Scripts\DoubleXPItem\DoubleXPManager.cs:81 
UnityEngine.Debug:Log (object)
DoubleXPManager:ConvertedStringToDate (string) (at Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs:87)
DoubleXPManager:Update () (at Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs:94)
```
چون توی try catch انداختی اررور رو نمیبینیم ولی داره اتفاق میوفته اگه فانکشن GetTime کار نکنه توی DoubleXPManager

2024-08-24 05:35 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/DoubleXPManager.cs
> +        }
میدونم سر این خیلی برو بیا داشتیم ولی منظورم اینطوری بود:
و اینکه دقت کردم فرمتی که انتخاب کردی ایننه : `yyyy-MM-ddHH:mm:ss` این اصلا اشکالی نداره ولی استاندارد نیست بین تاریخ و زمان یه T باید باشه، توی کد زیر مثالش هست اینو توی GlobalValue هم بزار لطفا
```suggestion
        DateTime parsedDate;
        DateTime.TryParseExact(insertedTime,"yyyy-MM-ddTHH:mm:ss",null,DateTimeStyles.None,out parsedDate);
        return parsedDate;
```

2024-08-24 05:41 UTC, m-nt commented on Assets/Atlas games/Scripts/APIManager.cs
> +                Debug.Log("Failed to get time: " + www.error);
```bash
Failed to get time: Unable to complete SSL connection
UnityEngine.Debug:Log (object)
APIManager/<GetCurrentDateAndTime>d__34:MoveNext () (at Assets/Atlas games/Scripts/APIManager.cs:167)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()
```
اینجا در امتداد درخواست های زیاد fail میشه و این اررور رو میده، لطفا وقتی این اتفاق افتاد یه fallback بزن به زمان local خود دستگاه که سیستم کار کنه در هرصورت، الان وقتی این fail میشه برمیگره به ابتدای تاریخ 😂

2024-08-24 05:42 UTC, m-nt requested changes
تغییرات لازمه

2024-08-24 17:19 UTC, m-nt commented on Assets/_FD/Script/GlobalValue.cs
> +        get { return PlayerPrefs.GetString("DoubleXp1HourDurationActivationTime", "1970-01-0100:00:01"); }
```suggestion
        get { return PlayerPrefs.GetString("DoubleXp1HourDurationActivationTime", "1970-01-01T00:00:01"); }
```

2024-08-24 17:56 UTC, m-nt approved these changes
بزن بره مرجو

2024-08-24 17:59 UTC, merged