28 add tutorials to the levels
mohamadnosratian/Fortress-defense pull request #113
Opened 2024-02-12 11:22 UTC by amirsafaricg

add tutorial to levels

2024-02-12 15:30 UTC, m-nt commented on Assets/PlayerPrefsEditor/CHANGELOG.md
> +## [1.2.2] - 2023-01-10
چرا PlayerPrefsEditor ویرایش شد ؟

2024-02-12 15:32 UTC, m-nt commented on Assets/Atlas games/Scripts/GameTutorial/TutorialFinder.cs
> +   // this script only prevents probable issues GameTutorial.cs might cause for finding UI parts in the tutorial tips
اگر این مربوطه به اون مشکل قدیمی که assetbundle نمیتونست یکسری ui هارو پیدا کنه، این دیگه اون مشکلو نداره! مگر اینکه داری توتوریال رو Instantiate میکنی!

2024-02-12 15:34 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/GameTutorial/TutorialFinder.cs
> +   // this script only prevents probable issues GameTutorial.cs might cause for finding UI parts in the tutorial tips
عه ؟ فقط برای رفع اون مشکل اینو زدم اگر مشکل ساز نیست، گیم آبجکت دریافت کنم ؟
قبلش هم با استفاده از اسم پارت های یو آی پیدا میکرد نه با استفاده از اساین کردن گیم ابجکت

2024-02-12 16:23 UTC, m-nt requested changes
تغییرات لازمه

2024-02-13 07:58 UTC, amirsafaricg commented
> تغییرات لازمه

هنوز کامل نشده صبر کنید. 
برنچ اندلس رو چک کردید؟

2024-02-25 16:57 UTC, m-nt commented on Assets/Atlas games/Scene/Playing atlas.unity
> +GameObject:
تغییراتی روی منوی اصلی گذاشتی اینجا.
دلیل این تغییرات چیه ؟

2024-02-25 17:01 UTC, m-nt commented
دلیل اینکه برای هر لول انیمیشن ساختی چیه،؟ ساختار tutorial عوض شده مگه ؟ یه توضیح بده داستان چیه.

2024-02-25 17:25 UTC, m-nt commented
مثلا این متقییر تغییر کرده، درسته این مورد ناچیزه و قابل چشم پوشی ولی کل مواظب باش:
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/3d552d29-c869-458c-b4f1-3d39d34ce285)

2024-02-25 17:28 UTC, m-nt commented
و همه level ها هم ویرایش شده. مثل این:
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/696d3d0a-1bb6-4cbf-bb5b-dab7d1189ac9)

2024-03-11 15:29 UTC, m-nt commented
## Error commit:
> https://github.com/atlasgames-repo/fortress-defense/pull/113/commits/d7537c282217896a50a04249a9ad91ca0e27418d
## Error State:
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/c0cfe683-138f-408d-aba9-d7afe332729f)
## Error Objects:
> GameTutorialSetup Prefab Instance > MainMenu, Trophies Variant, Map
## Error Scene: 
> SceneBackup/Playing Atlas.scene
## Error Stack:
```c#
NullReferenceException: Object reference not set to an instance of an object
GameTutorial.OpenTip () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:271)
GameTutorial.NextTip () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:112)
GameTutorial.StartTutorial () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:97)
GameTutorial+<OpenTutorialAtStart>d__25.MoveNext () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:88)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <31d5d65b32ec483292e13e8ae4100b93>:0)
```

2024-03-12 11:15 UTC, m-nt commented
> چرا PlayerPrefsEditor ویرایش شد ؟

این کامنت هایی که گذاشتم بی نتیجه مونده، تغییرات خیلی زیادی روی فایل های نامربوط داری، میدونی که من تایید نمیکنم اگه فایل نامربوط تغییری روش باشه دیگه ؟

2024-03-12 12:01 UTC, m-nt commented
> > ## Error commit:
> > > [d7537c2](https://github.com/atlasgames-repo/fortress-defense/commit/d7537c282217896a50a04249a9ad91ca0e27418d)
> > 
> > 
> > ## Error State:
> > ![image](https://private-user-images.githubusercontent.com/68176509/311759469-c0cfe683-138f-408d-aba9-d7afe332729f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzM3MDQsIm5iZiI6MTcxMDIzMzQwNCwicGF0aCI6Ii82ODE3NjUwOS8zMTE3NTk0NjktYzBjZmU2ODMtMTM4Zi00MDhkLWFiYTktZDdhZmUzMzI3MjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA4NTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwOThhODMwOGUzOGQ1ZTgzY2U4NzlhYzQ4MjJlYzEyNjc0M2E1YmEzYjRkZGIxN2Y1Y2E2YzRhYmVlMzFhODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sInEZG54uicrcu-0Yt2SFVtP998O3pHzD67q8Uq7u50)
> > ## Error Objects:
> > > GameTutorialSetup Prefab Instance > MainMenu, Trophies Variant, Map
> > 
> > 
> > ## Error Scene:
> > > SceneBackup/Playing Atlas.scene
> > 
> > 
> > ## Error Stack:
> > ```cs
> > NullReferenceException: Object reference not set to an instance of an object
> > GameTutorial.OpenTip () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:271)
> > GameTutorial.NextTip () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:112)
> > GameTutorial.StartTutorial () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:97)
> > GameTutorial+<OpenTutorialAtStart>d__25.MoveNext () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:88)
> > UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <31d5d65b32ec483292e13e8ae4100b93>:0)
> > ```
> 
> چک کنید دوباره ببینید هنوز مشکل هست ؟

آره توی منو بازی همچنان همون اررور برای آبجکت Trophies Variants هست

2024-03-12 12:56 UTC, amirsafaricg commented
> ```cs
> utorial.OpenTip () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:271)
> GameTutorial.NextTip () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:112)
> GameTutorial.StartTutorial () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:97)
> GameTutorial+<OpenTutorialAtStart>d__25.MoveNext () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:88)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections
> ```
یادم رفت بگم توتوریال ستاپ رو نیاز نیست تو dont destroy on load داشته باشید میتونید حذفش کنید. الان دونت دیستروی رو حذف میکنم.تو صحنه نباید حضور داشته باشه که مشکلی پیش نیاد


> کت های MainMenu و Trophies Variants

کامیتی که اینارو ایجاد کرد revert کردم

2024-03-12 13:02 UTC, amirsafaricg commented
> > > ## Error commit:
> > > > [d7537c2](https://github.com/atlasgames-repo/fortress-defense/commit/d7537c282217896a50a04249a9ad91ca0e27418d)
> > > 
> > > 
> > > ## Error State:
> > > ![image](https://private-user-images.githubusercontent.com/68176509/311759469-c0cfe683-138f-408d-aba9-d7afe332729f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzM3MDQsIm5iZiI6MTcxMDIzMzQwNCwicGF0aCI6Ii82ODE3NjUwOS8zMTE3NTk0NjktYzBjZmU2ODMtMTM4Zi00MDhkLWFiYTktZDdhZmUzMzI3MjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA4NTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwOThhODMwOGUzOGQ1ZTgzY2U4NzlhYzQ4MjJlYzEyNjc0M2E1YmEzYjRkZGIxN2Y1Y2E2YzRhYmVlMzFhODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sInEZG54uicrcu-0Yt2SFVtP998O3pHzD67q8Uq7u50)
> > > ## Error Objects:
> > > > GameTutorialSetup Prefab Instance > MainMenu, Trophies Variant, Map
> > > 
> > > 
> > > ## Error Scene:
> > > > SceneBackup/Playing Atlas.scene
> > > 
> > > 
> > > ## Error Stack:
> > > ```cs
> > > NullReferenceException: Object reference not set to an instance of an object
> > > GameTutorial.OpenTip () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:271)
> > > GameTutorial.NextTip () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:112)
> > > GameTutorial.StartTutorial () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:97)
> > > GameTutorial+<OpenTutorialAtStart>d__25.MoveNext () (at Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorial.cs:88)
> > > UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <31d5d65b32ec483292e13e8ae4100b93>:0)
> > > ```
> > 
> > 
> > چک کنید دوباره ببینید هنوز مشکل هست ؟
> 
> آره توی منو بازی همچنان همون اررور برای آبجکت Trophies Variants هست و همین طور داخل بازی برای آبجکت های MainMenu و Trophies Variants

این مشکل چیز غیرقابل پیش بینی ای نیست 
ولی باید یه تغییر کوچیکی بدم که مشکلی توش پیش نیاد توضیحات لازمه رو هم همین زیر میدم خدمتتون 


وقتی توی منو باشه طبق چیزی توی Atlas menu test هست یه آبجکت با اسکریپت Ui tutorial trigger هست 
اون گیم توتوریال ستاپ رو از توی فایل‌ها باز میکنه و توتوریال مد نظر رو لود میکنه 


ولی باید این آبجکت توی صحنه گیم مستقیما حضور داشته باشه 
ولی باید توتوریال‌هایی که مال منو هستن توش نباشن که ارور ندن. بخاطر مراحل اون توتوریال هست توی منوهای مختلف در حالت های مختلف یه سری آبجکت هایی که اینا باید پیدا کنن رو پیدا نمیکنن. الان درستش میکنم

2024-03-23 18:50 UTC, merged