Shop feature
mohamadnosratian/Fortress-defense pull request #141
Opened 2024-05-13 16:01 UTC by amirsafaricg

Shop menu with progressive grid menu applied 

still needs : 
- pop up animation for notifying the user
- image automatic size change for keeping the ration
- testing.

2024-05-14 18:19 UTC, m-nt commented
سورس برنچ درست نیست
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/d8192144-0be3-424a-96d7-60f4e9900ca8)

2024-05-14 18:25 UTC, m-nt commented on Assets/Atlas games/Scripts/Shop/Scripts/GridInfiniteScroll/Button.png
این اگه از پکیجی توی گیتهابه حواست باشه شرایط لایسنسش رعایت بشه.

2024-05-14 18:27 UTC, m-nt commented on Assets/Atlas games/Scripts/Shop/Scripts/ShopItem.cs
> +            User.Coin = -itemPrice;
اول سکه رو کم میکنی بعد پروسه خرید میره، این اشتباهه، آخر که اطمینان از درست پیش رفتن خرید اتفاق افتاد سکه کم کن که یوقت اگر به اررور خورد وسطش سکه کم نشه الکی

2024-05-14 18:55 UTC, m-nt commented on Assets/Atlas games/Scripts/Shop/Scripts/ShopPopup.cs
> +        _anim = GetComponent<Animator>();
اینو بهتر نیست تو Start یا OnEnable بگیری ؟

2024-05-14 18:57 UTC, m-nt commented on Assets/Atlas games/Scripts/Shop/Scripts/ShopPopup.cs
> +        {
تو این مدل شرطا تمرین کن از  Early return pattern استفاده کنی خیلی خوانایی بهتری داره.

2024-05-14 18:59 UTC, m-nt requested changes
تغییرات مورد نظر کامنت شده

2024-05-14 18:59 UTC, m-nt commented on Assets/Atlas games/Scripts/Shop/Scripts/ShopPopup.cs
> +        {
این نیاز به تغییر نیست، انتخوابیه تغییرش بدی نه زیاد مهم نیست.

2024-05-15 04:26 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/Shop/Scripts/ShopItem.cs
> +            User.Coin = -itemPrice;
آره 
حقیقت حواسم نبود دائما باید سکه بروز بشه 
صحیح فرمودید درستش میکنم.

2024-05-15 04:27 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/Shop/Scripts/ShopPopup.cs
> +        _anim = GetComponent<Animator>();
توی استارت فراخونی نمیشه
توی OnEnable فراخونیش میکنم.

2024-05-15 04:27 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/Shop/Scripts/ShopPopup.cs
> +        {
من باب تمرین و بهبود کار اصلاحش میکنم. مرسی :)

2024-05-26 18:10 UTC, m-nt requested changes

2024-05-26 18:10 UTC, m-nt commented on Assets/Atlas games/Scene/Menu atlas Test.unity
> -  m_ObjectHideFlags: 0
این آبجکت چیه پاک شده ؟

2024-05-26 18:10 UTC, m-nt commented on Assets/Atlas games/Scene/Menu atlas Test.unity
> -      propertyPath: StoreUI
اینم همین

2024-05-26 18:10 UTC, m-nt commented on Assets/Atlas games/Scripts/Shop/Scripts/ShopItem.cs
> +                            if (itemCount < maxAmount)
این تازه اضافه شده ؟ ولی الان که دارم میبینم 6 لایه شرط داری
کنترلش خیلی سخت میشه ، اینو حتما از Early return استفاده کن تا خانا تر بشه
اگه اونقدر پیچیدست که زدی و کار میکنه و تغییرش زمانبره مهم نیست، دست نزن

2024-07-14 06:21 UTC, m-nt commented
توی shop وقتی روی صفحه خالی scroll به سمت پایین انجام میشه اررور داریم:
```bash
MissingReferenceException: The object of type 'ShopItem' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
DynamicScrollRect.ScrollItem.get_RectTransform () (at Assets/Atlas games/Scripts/Shop/Scripts/GridInfiniteScroll/DynamicScrollRect/ScrollItem.cs:11)
DynamicScrollRect.ScrollContent.GetFirstItemPos () (at Assets/Atlas games/Scripts/Shop/Scripts/GridInfiniteScroll/DynamicScrollRect/ScrollContent.cs:123)
DynamicScrollRect.DynamicScrollRect.UpdateItems (UnityEngine.Vector2 delta) (at Assets/Atlas games/Scripts/Shop/Scripts/GridInfiniteScroll/DynamicScrollRect/DynamicScrollRect.cs:238)
DynamicScrollRect.DynamicScrollRect.OnScrollRectValueChanged (UnityEngine.Vector2 val) (at Assets/Atlas games/Scripts/Shop/Scripts/GridInfiniteScroll/DynamicScrollRect/DynamicScrollRect.cs:197)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <31d5d65b32ec483292e13e8ae4100b93>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <31d5d65b32ec483292e13e8ae4100b93>:0)
UnityEngine.UI.ScrollRect.LateUpdate () (at C:/Program Files/Unity/Hub/Editor/2020.2.5f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/ScrollRect.cs:863)
```
![image](https://github.com/user-attachments/assets/6b54488f-b88b-4d7c-bc68-cb05cdf86af6)

2024-07-14 06:27 UTC, m-nt commented
مسیر درست شاپ اینه :
![image](https://github.com/user-attachments/assets/1098ccde-f2a1-412e-814d-07e2fc9cfc21)

2024-07-18 07:28 UTC, m-nt commented on Assets/Atlas games/Scene/Menu atlas Test.unity
> +--- !u!1 &336024152
لطفا قبل از merge تغییرات سکانس های تستی رو بردار.

2024-07-18 07:29 UTC, m-nt reviewed
فعلا خوبه، همینو پیش برو!

2024-07-19 13:56 UTC, amirsafaricg commented
> روی صفحه خالی scroll به سمت پایین انجام میشه

رفع شد :)

2024-07-19 13:57 UTC, amirsafaricg commented on Assets/Atlas games/Scene/Menu atlas Test.unity
> -  m_ObjectHideFlags: 0
هرچی نگاه کردم نفهمیدم.

2024-08-10 06:33 UTC, m-nt commented on Assets/Atlas games/Scripts/ShopItems/RollingLog/ItemUsage.cs
> -    }
این کد کارش چی بود ؟ چرا خالی شده ؟

2024-08-10 06:50 UTC, m-nt commented
لطفا اسم گذاری هارو درست کن، Fortress shield بشه Activate fortress shield مثل بعقیه
![image](https://github.com/user-attachments/assets/36ee9e30-f521-4d61-b318-51965720060d)

2024-08-10 07:10 UTC, m-nt commented
یه نکته ای!
ایتم های Boost قراره که به تعداد محدود وجود داشته باشه، و از shop خریداری بشه. اینو یادت نره لطفا.
https://github.com/user-attachments/assets/49645cd4-9f9b-4501-8287-093313aa4f73

2024-08-10 07:12 UTC, m-nt commented
Log
نهایی نشده ؟ 
![image](https://github.com/user-attachments/assets/a31947d3-6d9e-4146-87f9-14221144e14d)
اینا خالی ان

2024-08-10 07:17 UTC, m-nt commented
یه نکته دیگه.
برای Shield حد اقل 3 تا عکس ازش بساز که درحال شکستنه و هر 30 درصد که کم میشه بره توی عکس ها و نشون بده که shield داره میشکنه .
و اینکه با توجه به این عکس، پایه shield قسمت پایین رو جدا کن و sorting order رو تنظیم کن تا زیر قلعه بیوفته.
![image](https://github.com/user-attachments/assets/c6f06535-14e8-4be5-8601-e0101699f212)

2024-08-10 07:59 UTC, m-nt requested changes
تعییرات لازمه

2024-08-11 06:29 UTC, amirsafaricg commented
> یه نکته ای! ایتم های Boost قراره که به تعداد محدود وجود داشته باشه، و از shop خریداری بشه. اینو یادت نره لطفا. https://github.com/user-attachments/assets/49645cd4-9f9b-4501-8287-093313aa4f73

یادم هست 
تا زمانی اینونتوری تکمیل نشه انجام هر کاری مربوط به این زمینه باعث وقوع دوباره کاری میشه

2024-08-11 06:30 UTC, amirsafaricg commented
> یه نکته دیگه. برای Shield حد اقل 3 تا عکس ازش بساز که درحال شکستنه و هر 30 درصد که کم میشه بره توی عکس ها و نشون بده که shield داره میشکنه . و اینکه با توجه به این عکس، پایه shield قسمت پایین رو جدا کن و sorting order رو تنظیم کن تا زیر قلعه بیوفته. ![image](https://private-user-images.githubusercontent.com/68176509/356795804-c6f06535-14e8-4be5-8601-e0101699f212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTgwMjksIm5iZiI6MTcyMzM1NzcyOSwicGF0aCI6Ii82ODE3NjUwOS8zNTY3OTU4MDQtYzZmMDY1MzUtMTRlOC00YmU1LTg2MDEtZTAxMDE2OTlmMjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA2Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYWY0ZDU1NDM3NzRmZWEyZjdlMTdmNTQ2MWQ1NWU4NGE4OTQ0OWE2YTRlNmJiMmRhNzZjNTNlNDU3Mzg1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Be0Gb3LpUcAkDD_EqhomNzoZlhgqOg2BxZpIjky8wmc) ![image](https://private-user-images.githubusercontent.com/68176509/356797886-85707c48-4541-4d11-8191-a5dc4fd1a35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTgwMjksIm5iZiI6MTcyMzM1NzcyOSwicGF0aCI6Ii82ODE3NjUwOS8zNTY3OTc4ODYtODU3MDdjNDgtNDU0MS00ZDExLTgxOTEtYTVkYzRmZDFhMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA2Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OTgxY2E0ZmE3MGYwMTBjZjdjOGVlZmZkNGZjY2I2NGMxNjkzZGI2ZjhiOGM4MWNlOWVjMDc0OGYyNjFkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EaG2PZXgdVzrdz-V7_kQjS2capsxKRD8TW8ZIagXcE0)

نیازی به دستکاری سورتینگ اوردر نیست 
asset مناسب داده بشه 
خود به خود حل میشه این مشکل 
و باشه چشم

2024-08-11 06:30 UTC, amirsafaricg commented
> Log نهایی نشده ؟ ![image](https://private-user-images.githubusercontent.com/68176509/356795630-a31947d3-6d9e-4146-87f9-14221144e14d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTgwMjksIm5iZiI6MTcyMzM1NzcyOSwicGF0aCI6Ii82ODE3NjUwOS8zNTY3OTU2MzAtYTMxOTQ3ZDMtNmQ5ZS00MTQ2LTg3ZjktMTQyMjExNDRlMTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA2Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjJhZTEyYjljOTVkMmFjMDgyZDQ2OTY4MzgxZDI2ZGI2ZWEwODIzMTkzZDIwZjFhMzk1YTQwMGRkNmNhYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C9ivdeTLf4nlxlssnLnI6XuS9usO2FeXXlaY75HAeFk) اینا خالی ان

چون asset نداریم که نهایی بشه.

2024-08-11 06:31 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/ShopItems/RollingLog/ItemUsage.cs
> -    }
چون گفتین تمام آیتم ها از توی BoostItemUI اجرا بشن دیگه احتیاجی به این کد به کلی نیست.

2024-08-12 05:39 UTC, m-nt commented
> > یه نکته دیگه. برای Shield حد اقل 3 تا عکس ازش بساز که درحال شکستنه و هر 30 درصد که کم میشه بره توی عکس ها و نشون بده که shield داره میشکنه . و اینکه با توجه به این عکس، پایه shield قسمت پایین رو جدا کن و sorting order رو تنظیم کن تا زیر قلعه بیوفته. ![image](https://private-user-images.githubusercontent.com/68176509/356795804-c6f06535-14e8-4be5-8601-e0101699f212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTgwMjksIm5iZiI6MTcyMzM1NzcyOSwicGF0aCI6Ii82ODE3NjUwOS8zNTY3OTU4MDQtYzZmMDY1MzUtMTRlOC00YmU1LTg2MDEtZTAxMDE2OTlmMjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA2Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYWY0ZDU1NDM3NzRmZWEyZjdlMTdmNTQ2MWQ1NWU4NGE4OTQ0OWE2YTRlNmJiMmRhNzZjNTNlNDU3Mzg1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Be0Gb3LpUcAkDD_EqhomNzoZlhgqOg2BxZpIjky8wmc) ![image](https://private-user-images.githubusercontent.com/68176509/356797886-85707c48-4541-4d11-8191-a5dc4fd1a35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTgwMjksIm5iZiI6MTcyMzM1NzcyOSwicGF0aCI6Ii82ODE3NjUwOS8zNTY3OTc4ODYtODU3MDdjNDgtNDU0MS00ZDExLTgxOTEtYTVkYzRmZDFhMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA2Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OTgxY2E0ZmE3MGYwMTBjZjdjOGVlZmZkNGZjY2I2NGMxNjkzZGI2ZjhiOGM4MWNlOWVjMDc0OGYyNjFkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EaG2PZXgdVzrdz-V7_kQjS2capsxKRD8TW8ZIagXcE0)
> 
> نیازی به دستکاری سورتینگ اوردر نیست asset مناسب داده بشه خود به خود حل میشه این مشکل و باشه چشم

ببین  خود به خود حل میشه یعنی چی ؟ تست کردی ؟ منظور من اینه که با است های دست ساز و موقت تست کن، تست نشده از کجا میدونی خود به خود حل میشه ؟

2024-08-12 05:41 UTC, m-nt commented
> > Log نهایی نشده ؟ ![image](https://private-user-images.githubusercontent.com/68176509/356795630-a31947d3-6d9e-4146-87f9-14221144e14d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTgwMjksIm5iZiI6MTcyMzM1NzcyOSwicGF0aCI6Ii82ODE3NjUwOS8zNTY3OTU2MzAtYTMxOTQ3ZDMtNmQ5ZS00MTQ2LTg3ZjktMTQyMjExNDRlMTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA2Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjJhZTEyYjljOTVkMmFjMDgyZDQ2OTY4MzgxZDI2ZGI2ZWEwODIzMTkzZDIwZjFhMzk1YTQwMGRkNmNhYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C9ivdeTLf4nlxlssnLnI6XuS9usO2FeXXlaY75HAeFk) اینا خالی ان
> 
> چون asset نداریم که نهایی بشه.

نداشتن است چه بهونه ایه ؟ خودت یچی دست ساز بزار موقت تا ببینیم چی زدی چطور کار میکنه

2024-08-12 05:45 UTC, m-nt commented on Assets/Atlas games/Scripts/Shop/Scripts/ShopItemData.cs
> +}
empty new line in end of file.

2024-08-12 05:47 UTC, m-nt requested changes
تغییر لازمه

2024-08-21 10:03 UTC, amirsafaricg commented
> دست ساز بزار موقت تا ببینیم چی زدی چطور کار

من بهونه نیاوردم پریفبش هست خواستید خودتون بذاریدش تو اسکریپت استفاده کنید!! 
کار کردن هم کار میکنه قبلا برای هادی و رسول پریفبی که میگین بهونه آوردم رو ست کرده بودم فیلم گرفتم فرستادم !!!!

2024-08-21 10:07 UTC, amirsafaricg commented
> > > یه نکته دیگه. برای Shield حد اقل 3 تا عکس ازش بساز که درحال شکستنه و هر 30 درصد که کم میشه بره توی عکس ها و نشون بده که shield داره میشکنه . و اینکه با توجه به این عکس، پایه shield قسمت پایین رو جدا کن و sorting order رو تنظیم کن تا زیر قلعه بیوفته. ![image](https://private-user-images.githubusercontent.com/68176509/356795804-c6f06535-14e8-4be5-8601-e0101699f212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTgwMjksIm5iZiI6MTcyMzM1NzcyOSwicGF0aCI6Ii82ODE3NjUwOS8zNTY3OTU4MDQtYzZmMDY1MzUtMTRlOC00YmU1LTg2MDEtZTAxMDE2OTlmMjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA2Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYWY0ZDU1NDM3NzRmZWEyZjdlMTdmNTQ2MWQ1NWU4NGE4OTQ0OWE2YTRlNmJiMmRhNzZjNTNlNDU3Mzg1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Be0Gb3LpUcAkDD_EqhomNzoZlhgqOg2BxZpIjky8wmc) ![image](https://private-user-images.githubusercontent.com/68176509/356797886-85707c48-4541-4d11-8191-a5dc4fd1a35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTgwMjksIm5iZiI6MTcyMzM1NzcyOSwicGF0aCI6Ii82ODE3NjUwOS8zNTY3OTc4ODYtODU3MDdjNDgtNDU0MS00ZDExLTgxOTEtYTVkYzRmZDFhMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA2Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OTgxY2E0ZmE3MGYwMTBjZjdjOGVlZmZkNGZjY2I2NGMxNjkzZGI2ZjhiOGM4MWNlOWVjMDc0OGYyNjFkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EaG2PZXgdVzrdz-V7_kQjS2capsxKRD8TW8ZIagXcE0)
> > 
> > 
> > نیازی به دستکاری سورتینگ اوردر نیست asset مناسب داده بشه خود به خود حل میشه این مشکل و باشه چشم
> 
> ببین خود به خود حل میشه یعنی چی ؟ تست کردی ؟ منظور من اینه که با است های دست ساز و موقت تست کن، تست نشده از کجا میدونی خود به خود حل میشه ؟

مهندس کدها رو خوندی ؟ 
نخوندی 
اگر خونده بودی متوجه میشدی این قیافه ای که حبابه گرفته فقط بخاطر اون اسپرایت دانلودی‌ایه که استفاده کردم چه ربطی داره ؟!
اینم asset اش : 
![file  Converted](https://github.com/user-attachments/assets/17b7079e-f241-440e-9070-7bf55f931761)


اگر متوجه توضیحاتم نشدید بگید متوجه نشدم نگید تست نکرده کد پوش کردم 
اینم فیلم نحوه کارکردش ! 

https://github.com/user-attachments/assets/b2ac3a3e-daee-469f-82d2-06d08789b24e

مسئله بشدت پایه‌ای و بیسیکه حباب که این شکلیه همون شکلی معلوم میشه و کاریشم نمیشه کرد و باید هم سورتینگ اردرش بندازتش روی قلعه به صورت overlay !

2024-08-28 06:13 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/ItemChecker.cs
> +}
```suggestion

}
```

2024-08-28 06:21 UTC, m-nt commented on Assets/_FD/Script/AffectZone.cs
>  }
```suggestion
}

```

2024-08-28 06:33 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/TimedItemManager.cs
>                                                            newDifferenceSeconds);
این متغییر استفاده نشده و اررور داره:
```bash
ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
Parameter name: value
System.DateTime.AddTicks (System.Int64 value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.DateTime.Add (System.Double value, System.Int32 scale) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.DateTime.AddSeconds (System.Double value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
TimedItemManager.CounterText (System.String theItemName) (at Assets/Atlas games/Scripts/DoubleXPItem/TimedItemManager.cs:122)
ItemActivator.CheckValue () (at Assets/Atlas games/Scripts/DoubleXPItem/ItemActivator.cs:22)
ItemActivator.Update () (at Assets/Atlas games/Scripts/DoubleXPItem/ItemActivator.cs:14)
```
```suggestion

```

2024-08-28 06:40 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/TimedItemManager.cs
> +            .AddHours(itemDuration());
اینم چون توی خط بعدی استفاده میشد ولی اون متغییر timeDifference استفاده ای نداشت، قاعدتا اینم استفاده نمیشه.
```suggestion

```

2024-08-28 06:56 UTC, m-nt commented on Assets/Atlas games/Scripts/DoubleXPItem/TimedItemManager.cs
>          _globalDate = await APIManager.instance.GetCurrentDateAndTime();
این یه مشکلی داره اینه که هردفعه که SetDate صدا زده میشه یه API call داریم برای دریافت زمان و این چون از نظر زمانی نزدیکه به هم بعضی از درخواست های سرور کار نمیکنه، این بهتره یک بار در ابتدا مثلا توی Start صدا زده بشه و از مقدارش استفاده بشه توی بعقیه موارد به جای اینکه هر دفعه صدا زده بشه .
در کل منظورم اینه که یه بار توی استارت صدا بزن اینو و مقدارشو یجا بزار و ازش استفاده کن.

2024-08-28 07:08 UTC, m-nt requested changes
تغییر لازمه

2024-08-29 07:09 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/DoubleXPItem/TimedItemManager.cs
>          _globalDate = await APIManager.instance.GetCurrentDateAndTime();
![image](https://github.com/user-attachments/assets/3d3ea117-bf48-4a8f-b100-7def5250becd)
همین الانم فقط توی awake فراخونی شده جای دیگه‌ای مورد استفاده قرار نگرفته

2024-08-29 07:11 UTC, amirsafaricg commented
موارد گفته شده اینجا حل شد‌
@m-nt

2024-09-29 07:21 UTC, m-nt approved these changes

2024-09-29 07:22 UTC, m-nt approved these changes

2024-09-29 07:23 UTC, m-nt commented
تایید مرج زدم! ببین اگر مشکل داره و تایید نشده بگو خودم بزنم مرج
@amirsafaricg

2024-09-29 08:05 UTC, m-nt approved these changes

2024-09-29 08:06 UTC, merged