Underground enemies
mohamadnosratian/Fortress-defense pull request #145
Opened 2024-05-16 09:38 UTC by amirsafaricg

Create a feature that allows enemies to spawn from under the ground near the fortress

2024-05-16 09:39 UTC, amirsafaricg commented
صرفا شما رو بعنوان کسی که ریویو قراره بکنه قرار دادم فیچر هنوز کار داره @m-nt

2024-06-23 06:30 UTC, m-nt commented
@amirsafaricg 
این وضعیتش چطوره ؟

2024-07-06 06:22 UTC, m-nt commented on Assets/GeneratedLevels/Playing atlas Test.unity
> -  m_FillClockwise: 1
لطفا تغییرات سکانس هارو اینطوری پوش نکن مگر از قبل هماهنگ شده و برای دلیل خاصی، 
همه است های سکانس ها prefab شده که به conflict نخوره سکانس ها! الان conflict خورده! اشکالی نداره این سکانس تستیه مهم نیست ولی به طور کلی برای لول های اصلی این پذیرفته نیست!

2024-07-06 06:24 UTC, amirsafaricg commented on Assets/GeneratedLevels/Playing atlas Test.unity
> -  m_FillClockwise: 1
دلیل اینکه از تستی استفاده میکنم هم دقیقا همینه

2024-07-06 06:26 UTC, m-nt commented on Assets/_FD/Script/SmartEnemy/SmartEnemyGrounded.cs
> +            foreach (SpriteRenderer sprite in characterSprites)
اینجا به بعد یه tab جلو رفته کد ها اینو لطفا درست کن. 
پیشنهادم اینه که از یه formatter خوب استفاده کنی برای فرمت کردن!

2024-07-06 06:28 UTC, m-nt commented on Assets/_FD/Script/SmartEnemy/SmartEnemyGrounded.cs
> +        yield return new WaitForSeconds(0f);
بجای این میتونی yield return null استفاده کنی که تا فریم بعدی صبر میکنه اگر قصدت این بوده.

2024-07-06 06:29 UTC, m-nt commented on Assets/_FD/Script/SmartEnemy/SmartEnemyGrounded.cs
> +            GameObject[] playerWarriors = GameObject.FindGameObjectsWithTag("Warrior");
دلیل اینکه tag هارد کد شده Warrior رو داری اینجا استفاده میکنی چیه ؟
اینو از حال hardcode خارج کن لطفا!

2024-07-06 06:34 UTC, amirsafaricg commented on Assets/_FD/Script/SmartEnemy/SmartEnemyGrounded.cs
> +            GameObject[] playerWarriors = GameObject.FindGameObjectsWithTag("Warrior");
چون فقط با این تگ کار دارم ؟

2024-07-06 06:35 UTC, m-nt commented on Assets/_FD/Script/SmartEnemy/SmartEnemyGrounded.cs
> +                }
از این دوتا حلقه میشه اینو برداشت کرد که Length هردو آرایه یکیه، نیازی به دوبار حلقه زدن نیست برای این درواقع حلقه اول بیفایدست:
```suggestion
                float[] warriorXPositions = new float[playerWarriors.Length];
                int chosenWarrior =0;
                for (int i = 0; i < playerWarriors.Length; i++)
                {
                    warriorXPositions[i] = playerWarriors[i].transform.position.x;
                    float xPosition = Mathf.Min(warriorXPositions);
                    if (xPosition == playerWarriors[i].transform.position.x)
                    {
                        chosenWarrior = i;
                    }
                }
```

2024-07-06 06:37 UTC, m-nt requested changes
تغییرات نیازه

2024-07-06 06:38 UTC, m-nt commented on Assets/GeneratedLevels/Playing atlas Test.unity
> -  m_FillClockwise: 1
آره متوجه ام ولی تغییرات ناخواسته رو لطفا نفرست روی گیتهاب

2024-07-06 06:39 UTC, m-nt commented on Assets/_FD/Script/SmartEnemy/SmartEnemyGrounded.cs
> +            GameObject[] playerWarriors = GameObject.FindGameObjectsWithTag("Warrior");
اگه بعدا تگ بخواد تغییر کنه چی ؟
لطفا اینو از hardcode خارج کن بزارش پیش بعقیه field های مربوطه به underground

2024-07-06 06:59 UTC, m-nt commented
این مدلی که پیاده کردی برای همه کاراکتر ها جواب نمیده! 
ما سه مدل داریم اینی که ساختی روی مدل default دشمنا جواب میده. اسکرین شات برای دشمنهاییه که با spine هستن.
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/9899509b-b5d5-44b4-90b6-d5ab1eaa2d48)

2024-07-06 07:00 UTC, m-nt commented on Assets/Atlas games/Scripts/UndergroundEnemy/Scripts/UndergroundHole.cs
> +    private AudioSource _source;
بجای AudioSource از AudioClip استفاده کن و از سیستم صدای خود بازی پخشش کن.
ref: SoundManager.cs

2024-07-06 07:02 UTC, m-nt commented on Assets/Atlas games/Scripts/UndergroundEnemy/Scripts/UndergroundHole.cs
> +    private Animator _anim;
این فیلد های private هیچ جایی set نمیشن و اررور میدن!
یا از private خارج کن یا توی Init ست کن
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/d35baf37-49c5-4da0-a841-150b417247b6)

2024-07-06 07:04 UTC, m-nt commented
لطفا روی همه سبک انمی تست کن. این پذیرفته نیست!
![image](https://github.com/atlasgames-repo/fortress-defense/assets/68176509/d9e2210d-6203-42c6-b2ef-1b3e478d9910)

2024-07-06 08:45 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/UndergroundEnemy/Scripts/UndergroundHole.cs
> +    private Animator _anim;
درست شد

2024-07-06 08:49 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/UndergroundEnemy/Scripts/UndergroundHole.cs
> +    private AudioSource _source;
با تابع PlaySFX انجام شد

2024-07-06 08:51 UTC, amirsafaricg commented on Assets/_FD/Script/SmartEnemy/SmartEnemyGrounded.cs
> +            foreach (SpriteRenderer sprite in characterSprites)
Done

2024-07-06 13:28 UTC, amirsafaricg commented
برای انمی‌های دارای اسپاین work arround ساخته شد. 
یک انمی در صحنه Playing atlas test ساخته شده و قرار داره بی زحمت چک بفرمایید. 
اصلاحات کدها هم اعمال شد.

2024-07-07 06:09 UTC, m-nt commented on Assets/Atlas games/Scripts/UndergroundEnemy/Scripts/UndergroundHole.cs
> +        _source = GetComponent<AudioSource>();
ما توی گیم سیستم مدیریت صدا داریم چرا از اون استفاده نمیکنی ؟

2024-07-07 06:12 UTC, m-nt commented on Assets/Atlas games/Scripts/UndergroundEnemy/Shaders/MeshMask.shader
> +}
به آخر فایل یه لاین خالی اضافه کن

2024-07-07 06:14 UTC, m-nt commented on Assets/_FD/Script/SoundManager.cs
> +    public void DiggingSound()
این فانکشن خالی برای چیه ؟

2024-07-07 06:15 UTC, m-nt requested changes
کامنتارو چک کن

2024-07-16 17:08 UTC, amirsafaricg commented
@m-nt یه سری بخش های کد تمیزکاری شد برای اسپاین  
قسمت های کوچیکی هستن شما بررسی بفرمایید بی زحمت 
این کامیت شامل پریفب انمی ها نمیشه البته

2024-07-17 06:35 UTC, amirsafaricg commented on Assets/_FD/Script/SoundManager.cs
> +    public void DiggingSound()
برای پلی شدن صدای کندن زمین

2024-07-17 06:36 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/UndergroundEnemy/Shaders/MeshMask.shader
> +}
انجام شد

2024-07-18 07:26 UTC, m-nt approved these changes
حله

2024-07-20 07:30 UTC, merged