Setting up level rewards system
mohamadnosratian/Fortress-defense pull request #177
Opened 2024-10-19 17:12 UTC by amirsafaricg

2024-10-21 13:48 UTC, amirsafaricg commented
@m-nt

2024-10-24 07:48 UTC, m-nt commented on Assets/GeneratedLevels/level 20.prefab
>        BossMaxExp: 50
چرا دشمن به guid bb4a391d19b886c41b2c33129326ffa1 از توی لول 20 پاک شد؟

2024-10-24 07:50 UTC, m-nt commented on Assets/GeneratedLevels/level 20.prefab
> +      spawnFromUnderground: 0
چرا دشمن به guid bb4a391d19b886c41b2c33129326ffa1 از توی لول 20 پاک شد؟

2024-10-24 08:47 UTC, m-nt commented on Assets/_FD/Script/GUI/MenuManager.cs
> +        }
به جای اینکه دوتا حلقه استفاده کنی اینجا میتونی از Linq استفاده کنی
فقط باید اول کد این رو ایمپورت کنی:
using System.Linq;
```suggestion
        int currentLevel = GlobalValue.levelPlaying;
        var _currentReward =
            from item in rewardList.rewards
            where item.rewardLevel == currentLevel
            select item;
        foreach (Reward reward in _currentReward) {
            rewardUI.SetActive(true);
            rewardUI.GetComponent<RewardMenu>().Init(reward,this);
            yield break;
        }
        VictotyUI.SetActive(true);
```

2024-10-24 09:07 UTC, m-nt requested changes
کامنت هارو چک کن! مواردی که اختیاریه مهم نیست زیاد مثل Linq ولی خوبه که تغییر رو اعمال کنی. بعد هم Linq رو چک کن خیلی کمکیه

2024-10-24 09:08 UTC, m-nt commented on Assets/_FD/Script/GUI/MenuManager.cs
> +        }
فقط حواست باشه این COmmint suggestion رو اگه بزنی اررور میگیره چون نیازه که using System.Linq; باشه حتما

2024-11-04 08:41 UTC, merged