Tutorial 2.0 ( improved tutorial system)
mohamadnosratian/Fortress-defense pull request #180
Opened 2024-11-15 16:23 UTC by amirsafaricg

Tutorial 2.0 is improved and optimized version of the current game tutorial system present in the project.

2024-11-21 12:04 UTC, amirsafaricg commented
@m-nt سلام 
کدها برای ریویو آماده هستن.

2024-11-22 11:40 UTC, m-nt commented on Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/GameTutorialManager.cs
این کد کاربردش چیه؟
Time.timeScale
مستقیم میتونی ازش استفاده کنی چرا یه متقییر جدید رو داری هر فریم براش استفاده میکنی.
متقیر time هم جایی استفاده نشده.

2024-11-22 11:45 UTC, m-nt commented on Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/GameTutorialManager.cs
>                  GameObject obj = Instantiate(setup.SceneTutorial(), FindObjectOfType<MenuManager>().transform.position, Quaternion.identity, FindObjectOfType<MenuManager>().transform);
این خط اررور داره.
```bash
NullReferenceException: Object reference not set to an instance of an object
GameTutorialManager.Start () (at Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/GameTutorialManager.cs:16)
```
یکی از مقدار های FindObjectOfType
پیدا نمیکنه.
و مورد بعدی اینکه دوبار داری این فانکشن رو به صورت inline صدا میزنی
لطفا یکبار جدا صدا بزنش و متقیرش رو چک کن که اگر پیدا نشد یه رفتار مناسب داشته باشه.

2024-11-22 11:53 UTC, m-nt commented on Assets/Atlas games/Scene/Menu atlas Test.unity
> +      objectReference: {fileID: 0}
تغییرات بسیار زیادی روی سکانس ها هست که بی دلیل قابل قبول نیست.
این تغییرات چیه و چرا ؟
هر سه سکانس رو لطفا توضیح بده.
Menu atlas Test.unity
Playing atlas Testing.unity
Playing atlas.unity

نکته. اضافه شدن مشکلی نداره ولی ویرایش های بسیاری اتفاق اتفاده که مثلا سکانس تست منو اصلی رفرنسش به پریفب HomeMenu رو از دست  داده،
یا اینکه مشکل از پریفبه.
الان در ادامه ریویو چک میکنم...

2024-11-22 11:55 UTC, m-nt commented on Assets/Atlas games/Prefab/Scene Prefabs/Playing Atlas/MenuManager.prefab
> +  isClickable: 0
فکر نکنم مشکل از پریفب باشه، اگر تغییرات روی سکانس ها بیدلیل هست لطفا برگردون تغییرات رو و سعی کن تا امکانش هست پریفب هارو ویرایش کنی و تنها در صورتی ویرایش سکانس مجازه که چیزی اضافه بشه یا حذف بشه(به صورت پریفب) یا توضیح داده بشه که مورد ویرایش شده چیه و چیکار میکنه.

2024-11-22 12:06 UTC, m-nt commented on Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/Dialog.cs
> +            case DialogContent.Image:
توی این switch
عملیات های تکراری زیادی هست.
با توجه به اینکه این فانکشن قراره از توی انیمیشن صدا زده بشه این ویژگی هست که متقییر DialogContent رو به صورت آرگومان به فانکشن بدی و مقدار رو توی انیمیشن تنظیم کنی. عکسشو بعد این متن میفرستم.
یا اگر امکانش نیست تمام اتفاقات تکراری توی switch رو خارج کن ازش

2024-11-22 12:06 UTC, m-nt commented on Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/Dialog.cs
> +            case DialogContent.Image:
![image](https://github.com/user-attachments/assets/56c4ff28-e6d0-484c-9510-266717d76309)

2024-11-22 12:15 UTC, m-nt commented on Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/TutorialNew.cs
> +                                rotationAngle = 180f;
template for instructions...

2024-11-22 12:37 UTC, m-nt requested changes
تغییر لارزمه

2024-11-24 08:40 UTC, amirsafaricg commented
اعمال شد موارد

2024-11-24 12:34 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/TutorialNew.cs
> +                                rotationAngle = 180f;
What ?!

2024-11-25 08:14 UTC, m-nt commented on Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/GameTutorialManager.cs
> +                    obj.GetComponent<TutorialNew>().InitTutorial();
این FindObjectOfType رو لطفا از حالت inline خارج کن
تا اررور هارو بتونی بگیری.
```bash
NullReferenceException: Object reference not set to an instance of an object
GameTutorialManager.Start () (at Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/GameTutorialManager.cs:16)
```

2024-11-25 08:32 UTC, m-nt commented on Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/GameTutorialManager.cs
> +                }
```suggestion
                {
                    MenuManager manager = FindObjectOfType<MenuManager>();
                    if (manafer == null) {
                        // do something logical
                        return;
                    }
                    GameObject obj = Instantiate(setup.SceneTutorial(), manager.transform.position, Quaternion.identity, manager.transform);
                    obj.transform.SetSiblingIndex(manager.transform.childCount - 1);
                    obj.GetComponent<TutorialNew>().InitTutorial();
                }
```

2024-11-25 08:49 UTC, m-nt commented on Assets/_FD/Script/AffectZoneButton.cs
> +        print(GlobalValue.IsMagicUsedForTheFirstTime);
پرینت ها رو بعد اینکه کدت کار کرد پاک کن لطفا.

2024-11-25 08:53 UTC, m-nt commented on Assets/_FD/Script/AffectZoneButton.cs
> +        XPTxt.text = GlobalValue.IsMagicUsedForTheFirstTime == 0 ? "" : $"{xp_text_prefix}{XPConsume}";
چون هر دفعه GlobalValue داره از PlayerPrefs استفاده میکنه برای لود اطلاعات از فایل 
این عملیت کنده.
بهترین کار اینه که توی Start اینو یه بار لود کنی و نتیجه شرط رو توی یک متغییر private ذخیره کنی و توی بعقیه موارد 
کد از متغییر استفاده کنی به جای اینکه هر دفعه همینو صدا کنی.
مگر اینکه وابستگی لحظه ای داشته باشی به این متغییر.

2024-11-25 08:54 UTC, m-nt commented on Assets/_FD/Script/AffectZoneButton.cs
> +        can_pay = GlobalValue.IsMagicUsedForTheFirstTime == 0 ? true : GameManager.Instance.currentExp >= XPConsume;
در رابطه با کامنت قبلی.
این عملیت هم کنده هم داره توی آپدیت چک میشه.
اینو میتونی توی Start یک بار چک کنی و اینجا از متغییرش استفاده کنی.

2024-11-25 08:56 UTC, m-nt commented on Assets/_FD/Script/AffectZoneButton.cs
> +        XPTxt.text = GlobalValue.IsMagicUsedForTheFirstTime == 0 ? "" : $"{xp_text_prefix}{XPConsume}";
```suggestion
        first_time_magic_user = GlobalValue.IsMagicUsedForFirstTime == 0;
        XPTxt.text = first_time_magic_user ? "" : $"{xp_text_prefix}{XPConsume}";
```

2024-11-25 08:57 UTC, m-nt commented on Assets/_FD/Script/AffectZoneButton.cs
> +        can_pay = GlobalValue.IsMagicUsedForTheFirstTime == 0 ? true : GameManager.Instance.currentExp >= XPConsume;
```suggestion
        can_pay = first_time_magic_use ? true : GameManager.Instance.currentExp >= XPConsume;
```

2024-11-25 08:58 UTC, m-nt commented on Assets/_FD/Script/AffectZoneButton.cs
```suggestion
    private bool first_time_magic_use;
```

2024-12-07 12:07 UTC, amirsafaricg commented on Assets/_FD/Script/GUI/MenuManager.cs
>          VictotyUI.SetActive(true);
برمیگردونم به لینک و اگر مشکلی بود رفع میکنم

2024-12-07 12:09 UTC, amirsafaricg commented on Assets/_FD/Script/AffectZoneButton.cs
> +        print(GlobalValue.IsMagicUsedForTheFirstTime);
✔️

2024-12-07 15:00 UTC, amirsafaricg commented
@m-nt  
لطفا ریویو کنید موارد چک شد 
اعمال شد 
قفل ایکس پی مجیک ها هم اصلا جور دیگه ای باید پیاده سازی میشد و اصلاح شد بی زحمت ریویو کنید.

2024-12-08 15:41 UTC, m-nt commented on Assets/Atlas games/Scripts/Tutorial 2.0/Scripts/GameTutorialManager.cs
> +                        // do something logical
این کامنت برای این بود که یه کاری انجام بدی وقتی که manager مقدارش null باشه.
اگه با همون return خالی درست اجرا میشه و مشکلی نداره، اوکیه.
این کامنتو میزارم که مطمعن بشم بررسی کرده باشی

2024-12-08 15:52 UTC, m-nt commented
گوشه سمت چپ تصویر ماسک کامل صفحه رو نپوشونده! به جز این چیز دیگه ای ندیدم عالیه!
آمادست برای مرج
![image](https://github.com/user-attachments/assets/ce6bff96-b85e-4206-b401-0cb26d8304d8)

2024-12-15 06:28 UTC, amirsafaricg commented
مشکل از Click preventer بود که هم سایز با rect آبجت مادر توتوریال نبود 
رفع شد پوش شد بی زحمت ریویو بفرمایید @m-nt

2024-12-15 06:45 UTC, m-nt approved these changes
done

2024-12-15 15:49 UTC, merged