Game tutorial completed
mohamadnosratian/Fortress-defense pull request #22
Opened 2023-07-11 06:36 UTC by amirsafaricg

Game tutorial completed with more vast types of tutorials:
- tips (legacy)
- pop up
- task

2023-07-11 06:37 UTC, amirsafaricg commented
https://github.com/Atlas-Games-Repo/Fortress-defense/assets/77434000/c03d1c09-c299-434c-b47c-539f428af39e

ویدئو آموزش به صورت جدید : 
tip داریم که عین قبلیه 
dialog داریم که یه صفحه باز میشه 
task داریم که میگه مثلا یه کاری توی بازی توسط کاربر انجام شه (فلش قرمز)

طبق معمول اوپن ماژول هست برای هرچیزی میتونید آموزش رو بدین صورت با ترکیب دلخواه در بیارید، جوری ساختمش که انیمیشن های مختلف هرچی دلتون بخواد بتونید بدون عیب از همین الان پیدا کنید برای بخش آموزش

2023-07-11 06:38 UTC, amirsafaricg commented
منتظر review شما و راهنماییتون برای رفع این conflict هم هستم

2023-07-11 11:31 UTC, m-nt commented
> منتظر review شما و راهنماییتون برای رفع این conflict هم هستم کد endless بخاطر اینکه از پروژه پاک شد و دوباره اضافه اش کردم این ارور رو داده حالا من دقیق نمیدونم معنی این ارور از چیه شما یه بررسی بفرمایید به منم اطلاع بدید

کدو الان بررسی میکنم، این بار کانفلیکت رو میتونی همینجا حل کنی، Resolve conflict . اگه نمیتونی من حلش میکنم مشکلی نیست، توی ویدو که عالی شده خسته نباشی

2023-07-11 14:04 UTC, m-nt commented
![image](https://github.com/Atlas-Games-Repo/Fortress-defense/assets/68176509/6ed02e3b-817a-4db9-92c2-984d23f84f69)
اینطوری باید کانفلیکت رو حل کنی:
به انوان مثال توی این عکس بستگی به اینکه کدوم رو میخوای نگه داری باید یکی از این مربع هارو حذف کنی.
حذف قسمت آبی برای اینکه تغییرات game-toturial-compelition رو نگه داری و برعکس.

2023-07-11 14:36 UTC, m-nt commented
چرا اینجا دکمه های دیگه دارن کار میکنن ؟
![image](https://github.com/Atlas-Games-Repo/Fortress-defense/assets/68176509/57aa1eed-24eb-42e7-82ac-9e5658d69e87)
میتونی mask کنی صفحه به جز اون قسمت که فقط بتونه اونجا رو کلیک کنه

2023-07-11 14:48 UTC, m-nt requested changes
لطفا تغییرات لازمه رو اعمال کن، در کل عالی شده 👌
نکته مهم تر اینکه هنوز تو مرحله develop مونده این و قابل اجرا نیست از منوی اصلی، این بالا میمونه تا اینکه این مورد هم تکمیل بشه یا اینکه میتونی بعد merge شدن این PR یکی دیگه بازی کنی برای پیاده سازی کامل tutorial ها. یعنی:
* حالت endless از منو بازی قابل بازی باشه، و از حالت dev خارج بشه.
* بعقیه tutorial ها هم اضافه بشه.

2023-07-11 14:48 UTC, m-nt commented on Assets/Atlas games/Scripts/UI/GameTutorial.cs
> +                            switch (nextSetup.pointerDirection)
اینجا 5 لایه nesting داری، ببین اگه میتونی کمترش کن، اگر هم که خیلی به دردسر میخوری نیازی نیست

2023-07-11 19:27 UTC, amirsafaricg commented
> چرا اینجا دکمه های دیگه دارن کار میکنن ؟

چون Button نیستن چیز دیگه‌ای استفاده شده براشون میرم بررسی میکنم

2023-07-11 19:28 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/UI/GameTutorial.cs
> +                            switch (nextSetup.pointerDirection)
اوکی بررسی میکنم

2023-07-11 19:29 UTC, amirsafaricg commented
> نکته مهم تر اینکه هنوز تو مرحله develop مونده این و قابل اجرا نیست از منوی اصلی، این بالا میمونه تا اینکه این مورد هم تکمیل بشه یا اینکه میتونی بعد merge شدن این PR یکی دیگه بازی کنی برای پیاده سازی کامل tutorial ها. یعنی:

منظورتون اندلس هستش که از منو قابل اجرا نیست؟ 
برای توتوریال باید لیست بهم بدن به هادی میگم ممنون

2023-07-13 14:33 UTC, m-nt requested changes
Solve the Conflict

2023-07-24 06:54 UTC, m-nt commented on Assets/Atlas games/Scripts/UI/GameTutorial/GameTutorialManager.cs
> +       GameObject obj = Instantiate(_setup.SceneTutorial().gameObject, FindObjectOfType<Canvas>().transform.position,
یه چک بذار که اگه _setup پیدا نشد و null بود چی بشه.

2023-07-24 06:58 UTC, m-nt submitted a review, later dismissed
بیشترش اوکیه، اون کامنت هم آپشنال هست.
اگه انجامش بدی که چه بهتر. کانفلیکت رو حل کن و merge کن. خسته نباشی

2023-08-02 09:48 UTC, m-nt approved these changes
اوکیه مرج کن بره

2023-08-02 09:51 UTC, m-nt approved these changes
;/

2023-08-02 10:13 UTC, amirsafaricg commented
> ;/

؟

2023-08-02 16:14 UTC, merged