Story feature
mohamadnosratian/Fortress-defense pull request #24
Opened 2023-07-13 12:19 UTC by amirsafaricg

Story feature delivered with :
- supporting any amount of slides
- supporting any amount of different fading speeds and showing times
- pauses game automatically and unpauses after the slides
- typewritter effect on subtitles and supports any type speed as wanted

https://github.com/Atlas-Games-Repo/Fortress-defense/assets/77434000/332b2770-7602-456c-ba39-6badf3e490e5

2023-07-13 13:09 UTC, amirsafaricg commented
تغییری که هادی میخواست اعمال شه :
https://github.com/Atlas-Games-Repo/Fortress-defense/assets/77434000/5339c669-d57a-4086-aa5c-0b197855b8ef

2023-07-13 14:47 UTC, m-nt commented on Assets/Atlas games/Scripts/UI/Story.cs
> +}
```suggestion
}

```

2023-07-13 14:49 UTC, m-nt commented on Assets/Atlas games/Scripts/UI/Test assets/atlasgamesio_2d_animation_In_the_ice_city_The_aftermath_of_an_724b7bca.png
لطفا فرمت عکس رو تغییر بده و سایز رو کم کن، از کمپرس های خود یونیتی استفاده کن

2023-07-13 14:49 UTC, m-nt commented on Assets/Atlas games/Scripts/UI/Test assets/atlasgamesio_2d_animation_The_aftermath_of_an_apocalyptic_eve_a6accb9c.png
مشابه قبلی

2023-07-13 14:49 UTC, m-nt commented on Assets/Atlas games/Scripts/UI/Test assets/atlasgamesio_2d_animation_imagineEnter_a_realm_plagued_by_the_0b77cf42.png
مشابه قبلی

2023-07-13 14:49 UTC, m-nt commented on Assets/Atlas games/Scripts/UI/Test assets/atlasgamesio_imagineIn_the_aftermath_of_an_apocalyptic_event_w_19135582.png
مشابه قبلی

2023-07-13 14:53 UTC, m-nt requested changes
لطفا تغییرات مد نظر رو اعمال کن و یک نکته دیگه، لطفا scene اصلی بازی رو تمیز نگه دار :
![image](https://github.com/Atlas-Games-Repo/Fortress-defense/assets/68176509/50e2219d-8a63-4a98-b25a-07ca6b6bce71)
این icon توتوریال رو تغییر بده به همون کتاب.
یه سوال، این هم به صورت ماژول هست درسته ؟ که بعدا به مراحل مختلف اضافش کنی ؟ راه پیاده سازی داره برای مراحل مختلف ؟ 
میدونی که مراحل مختلف ما توی فقط یک scene اجرا میشه

2023-07-13 14:54 UTC, m-nt commented
راستی conflict رو هم حل کن لطفا

2023-07-15 13:09 UTC, amirsafaricg commented on Assets/Atlas games/Scripts/UI/Story.cs
> +            text.text = captionString.Substring(0, charactersTyped);
خطا نمیده برای من جدی

2023-07-24 06:50 UTC, m-nt submitted a review, later dismissed
از نظر کدی همه چی اوکیه، توی یونیتی تست نکردم به نظرم کلا اوکیه، کانفلیکت رو حل کن و خودت merge کن، خسته نباشی

2023-08-02 09:41 UTC, m-nt commented on Assets/Atlas games/Scene/Playing atlas endless.unity
> +  m_PrefabAsset: {fileID: 0
این باگ داره، آبجکت JSON تایپ هست و باید { بسته بشه.
لطفا چک کن جای دیگه چنین چیزی نباشه

2023-08-02 09:42 UTC, m-nt requested changes
تغییر نیازه

2023-08-02 10:21 UTC, amirsafaricg commented
> تغییر نیازه

توضیحتون خیلی ناقصه کامل تر بگید لطفا چیو تغییر توی چی نیازه الان ؟

2023-08-02 10:48 UTC, m-nt commented
> > تغییر نیازه
> 
> توضیحتون خیلی ناقصه کامل تر بگید لطفا چیو تغییر توی چی نیازه الان ؟


https://github.com/Atlas-Games-Repo/Fortress-defense/pull/24#discussion_r1281664490

2023-08-02 16:25 UTC, m-nt approved these changes
👌

2023-08-02 16:25 UTC, merged